# Generated by Django 5.1.15 on 2026-05-20 19:53

import django.contrib.postgres.fields
import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, unique=True, verbose_name='Название (рус)')),
                ('name_en', models.CharField(max_length=200, unique=True, verbose_name='Название (англ)')),
            ],
            options={
                'verbose_name': 'География (система)',
                'verbose_name_plural': 'Географии (системы)',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(help_text='Двух- или трёхбуквенный ISO-код: ru, en, evn, sah, ...', max_length=10, unique=True, verbose_name='ISO 639')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Название (рус)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Название (англ)')),
                ('name_native', models.CharField(blank=True, help_text='Как язык называется на самом себе (для эвенкийского — Эвэды̄ турэ̄н)', max_length=100, verbose_name='Самоназвание')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['iso'],
            },
        ),
        migrations.CreateModel(
            name='MotivationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name_ru', models.CharField(max_length=200, unique=True, verbose_name='Короткое имя (рус)')),
                ('short_name_en', models.CharField(max_length=200, unique=True, verbose_name='Короткое имя (англ)')),
                ('comment_ru', models.TextField(blank=True, verbose_name='Комментарий (рус)')),
                ('comment_en', models.TextField(blank=True, verbose_name='Комментарий (англ)')),
            ],
            options={
                'verbose_name': 'Мотив наименования',
                'verbose_name_plural': 'Мотивы наименования',
                'ordering': ['short_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('comment', models.TextField(blank=True, help_text='Биографические сведения, аффилиация, год рождения', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Информант / автор',
                'verbose_name_plural': 'Информанты и авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Библиографическая ссылка, описание архивного дела, или экспедиционных данных', unique=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (англ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (англ)')),
                ('icon', models.CharField(blank=True, help_text="Имя иконки в MapLibre sprite-sheet, например 'river'", max_length=50, verbose_name='Иконка (имя в спрайте)')),
                ('default_color', models.CharField(blank=True, help_text='HEX-цвет для отображения на карте, например #2e7d32', max_length=20, verbose_name='Цвет по умолчанию')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponyms.language', verbose_name='Язык, к которому относится тип')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['sort_order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name_ru', models.CharField(max_length=500, verbose_name='Регион (рус)')),
                ('area_name_en', models.CharField(max_length=500, verbose_name='Регион (англ)')),
                ('date_collected', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('place_collected', models.TextField(blank=True, verbose_name='Место получения')),
                ('image_link', models.URLField(blank=True, verbose_name='Ссылка на скан карты')),
                ('scanned_image', models.ImageField(blank=True, null=True, upload_to='historical_maps/%Y/', verbose_name='Скан карты (файл)')),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Центр: широта')),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Центр: долгота')),
                ('comment_collected_ru', models.TextField(blank=True, verbose_name='Комментарий (рус)')),
                ('comment_collected_en', models.TextField(blank=True, verbose_name='Комментарий (англ)')),
                ('is_archive', models.BooleanField(default=False, help_text='Отметить, если карта получена из архива (для отличия от полевых данных)', verbose_name='Архивная карта')),
                ('geo_systems', models.ManyToManyField(blank=True, related_name='historical_maps', to='toponyms.geosystem', verbose_name='Географические системы')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_maps', to='toponyms.person', verbose_name='Автор карты')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_maps', to='toponyms.person', verbose_name='Собиратель')),
            ],
            options={
                'verbose_name': 'Рукописная карта',
                'verbose_name_plural': 'Рукописные карты',
                'ordering': ['area_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Может быть пустой, если точные координаты неизвестны', max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Может быть пустой, если точные координаты неизвестны', max_digits=9, null=True, verbose_name='Долгота')),
                ('osm_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID объекта в OpenStreetMap (для связи с базой OSM)', null=True, verbose_name='OSM ID')),
                ('is_coordinates_approximate', models.BooleanField(default=False, help_text='Отметить, если точные координаты неизвестны и место указано в районе карты', verbose_name='Координаты приблизительные')),
                ('location_comment', models.TextField(blank=True, help_text='Например: «5 км вверх по реке от Х», «на левом берегу»', verbose_name='Комментарий к локализации')),
                ('is_duplicate', models.BooleanField(default=False, help_text='Отметить если место дублирует другую запись', verbose_name='Дубликат')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_places', to='toponyms.person', verbose_name='Редактор данных')),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='toponyms.featuretype', verbose_name='Тип объекта')),
                ('historical_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='toponyms.historicalmap', verbose_name='Рукописная карта')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['-date_added'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_original', models.TextField(verbose_name='Оригинальный текст')),
                ('language_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_narrations', to='toponyms.language', verbose_name='Язык оригинала')),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narrations', to='toponyms.person', verbose_name='Рассказчик')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrations', to='toponyms.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Нарратив',
                'verbose_name_plural': 'Нарративы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Toponym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя места на выбранном языке и в принятой для него орфографии', max_length=300, verbose_name='Имя (как записано)')),
                ('name_latin', models.CharField(blank=True, help_text='Научная транслитерация. Автогенерируется из кириллицы.', max_length=300, verbose_name='Латиница (для эвенкийского)')),
                ('name_ipa', models.CharField(blank=True, help_text='Фонетическая транскрипция в IPA', max_length=300, verbose_name='IPA транскрипция (для эвенкийского)')),
                ('translation_ru', models.CharField(blank=True, help_text='Перевод значения имени на русский. Например, «Бира» → «река»', max_length=300, verbose_name='Перевод (рус)')),
                ('translation_en', models.CharField(blank=True, max_length=300, verbose_name='Перевод (англ)')),
                ('motivation_comment', models.TextField(blank=True, verbose_name='Комментарий к мотивации')),
                ('linguistic_means', models.TextField(blank=True, help_text='Морфемный анализ, словообразовательная характеристика', verbose_name='Лингвистические средства')),
                ('number_on_map', models.CharField(blank=True, help_text='Номер точки на рукописной карте', max_length=20, verbose_name='Номер на карте')),
                ('alternative_forms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, help_text='Диалектные варианты, орфографические вариации', size=None, verbose_name='Альтернативные формы')),
                ('historical_map', models.ForeignKey(blank=True, help_text='На какой рукописной карте имя зафиксировано', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toponyms', to='toponyms.historicalmap', verbose_name='Карта (где записано)')),
                ('informant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_toponyms', to='toponyms.person', verbose_name='Информант')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toponyms', to='toponyms.language', verbose_name='Язык')),
                ('motivation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toponyms', to='toponyms.motivationtype', verbose_name='Мотив наименования')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toponyms', to='toponyms.place', verbose_name='Место')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toponyms', to='toponyms.sourcereference', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Топоним (имя)',
                'verbose_name_plural': 'Топонимы (имена)',
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='NarrationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст перевода')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narration_translations', to='toponyms.language', verbose_name='Язык перевода')),
                ('narration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='toponyms.narration', verbose_name='Оригинал')),
            ],
            options={
                'verbose_name': 'Перевод нарратива',
                'verbose_name_plural': 'Переводы нарративов',
                'unique_together': {('narration', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='toponyms_pl_latitud_1e4ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['feature_type', 'historical_map'], name='toponyms_pl_feature_b6f8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['language', 'name'], name='toponyms_to_languag_218170_idx'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['historical_map'], name='toponyms_to_histori_5aa226_idx'),
        ),
    ]
