# Generated by Django 5.1.15 on 2026-05-16 15:03

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
import wagtail.fields
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, help_text="Имя иконки в MapLibre sprite-sheet, например 'river' или 'mountain'", max_length=50, verbose_name='Иконка (имя в спрайт-шите)')),
                ('default_color', models.CharField(blank=True, help_text='HEX-цвет для отображения на карте, например #2e7d32', max_length=20, verbose_name='Цвет по умолчанию')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео'), ('document', 'Документ')], max_length=20, verbose_name='Тип')),
                ('file', models.FileField(upload_to='media_items/%Y/%m/', verbose_name='Файл')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('credit', models.CharField(blank=True, max_length=300, verbose_name='Источник/автор')),
                ('license', models.CharField(blank=True, help_text='Например: CC BY-SA 4.0, © Автор, public domain', max_length=100, verbose_name='Лицензия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Медиа-объект',
                'verbose_name_plural': 'Медиа-объекты',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-ключ')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('bbox_west', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_south', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_east', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_north', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL-ключ')),
                ('description', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})}, verbose_name='Описание')),
                ('creator', models.CharField(blank=True, help_text='Кто составил карту: имя информанта, коллектив, организация', max_length=300, verbose_name='Автор/информант')),
                ('date_drawn', models.CharField(blank=True, help_text="Может быть приблизительной: '1970-е', 'около 1965', точная дата", max_length=100, verbose_name='Дата составления')),
                ('date_collected', models.DateField(blank=True, null=True, verbose_name='Дата получения в проект')),
                ('language', models.CharField(blank=True, help_text='ISO-код: evn, ru, en, ...', max_length=10, verbose_name='Язык подписей на карте')),
                ('scanned_image', models.ImageField(upload_to='historical_maps/%Y/', verbose_name='Скан карты (высокое разрешение)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Опционально — если не указано, генерируется автоматически из скана', null=True, upload_to='historical_maps/thumbnails/%Y/', verbose_name='Превью')),
                ('georeference_status', models.CharField(choices=[('none', 'Не привязана'), ('partial', 'Частичная привязка'), ('full', 'Полная привязка')], default='none', max_length=20, verbose_name='Статус геопривязки')),
                ('georeference_data', models.JSONField(blank=True, help_text='Allmaps Georeference Annotation: GCP-точки и параметры преобразования', null=True, verbose_name='Данные геопривязки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('related_media', models.ManyToManyField(blank=True, related_name='historical_maps', to='toponyms.mediaitem', verbose_name='Связанные медиа')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_maps', to='toponyms.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Рукописная карта',
                'verbose_name_plural': 'Рукописные карты',
                'ordering': ['-date_collected', 'title'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Toponym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_evn_cyrillic', models.CharField(blank=True, help_text='Стандартная орфография РФ', max_length=200, verbose_name='Эвенкийское (кириллица)')),
                ('name_evn_latin', models.CharField(blank=True, help_text='Научная транслитерация (можно сгенерировать из кириллицы)', max_length=200, verbose_name='Эвенкийское (латиница)')),
                ('name_evn_ipa', models.CharField(blank=True, help_text='Фонетическая транскрипция', max_length=200, verbose_name='Эвенкийское (IPA)')),
                ('name_evn_variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Диалектные варианты, исторические записи', size=None, verbose_name='Альтернативные эвенкийские формы')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Русское название')),
                ('name_ru_variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None, verbose_name='Альтернативные русские формы')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Английская запись')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('confidence', models.CharField(choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая'), ('unknown', 'Не определена')], default='medium', max_length=20, verbose_name='Точность локализации')),
                ('etymology', wagtail.fields.RichTextField(blank=True, verbose_name='Этимология')),
                ('narrative', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})}, verbose_name='Нарратив/история')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toponyms', to='toponyms.featuretype', verbose_name='Тип объекта')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toponyms', to='toponyms.region', verbose_name='Регион')),
                ('related_media', models.ManyToManyField(blank=True, related_name='toponyms', to='toponyms.mediaitem', verbose_name='Медиа')),
                ('related_toponyms', models.ManyToManyField(blank=True, to='toponyms.toponym', verbose_name='Связанные топонимы')),
            ],
            options={
                'verbose_name': 'Топоним',
                'verbose_name_plural': 'Топонимы',
                'ordering': ['name_ru'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ToponymOnMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_x', models.IntegerField(blank=True, null=True, verbose_name='X на скане (пиксели)')),
                ('pixel_y', models.IntegerField(blank=True, null=True, verbose_name='Y на скане (пиксели)')),
                ('label_as_written', models.CharField(blank=True, help_text='Как именно записан этот топоним на этой конкретной карте', max_length=300, verbose_name='Подпись на карте')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('historical_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toponym_positions', to='toponyms.historicalmap')),
                ('toponym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_positions', to='toponyms.toponym')),
            ],
            options={
                'verbose_name': 'Топоним на карте',
                'verbose_name_plural': 'Топонимы на картах',
                'unique_together': {('toponym', 'historical_map')},
            },
        ),
        migrations.AddField(
            model_name='toponym',
            name='source_maps',
            field=models.ManyToManyField(related_name='toponyms', through='toponyms.ToponymOnMap', to='toponyms.historicalmap', verbose_name='Связанные рукописные карты'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='toponyms_to_search__0bbbd1_gin'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['latitude', 'longitude'], name='toponyms_to_latitud_ac7bff_idx'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['feature_type', 'region'], name='toponyms_to_feature_deb036_idx'),
        ),
    ]
