# Generated by Django 5.1.15 on 2026-05-16 15:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Место')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Краткое описание')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})})),
            ],
            options={
                'verbose_name': 'Событие',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вводный текст')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})})),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вводный текст')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})})),
                ('icon', models.CharField(blank=True, help_text="Имя иконки lucide-react, например 'book', 'map', 'users'", max_length=50, verbose_name='Иконка')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name': 'Раздел',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})})),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Статья',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMemberPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Роль в проекте')),
                ('affiliation', models.CharField(blank=True, max_length=300, verbose_name='Аффилиация')),
                ('bio', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('map_embed', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст цитаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Автор/источник', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к карте', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Фильтр по региону; пусто — без фильтра', 'label': 'Регион (slug)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Показать только топонимы, связанные с этой рукописной картой', 'label': 'Рукописная карта (slug)', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Высота, px'}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('region_slug', 7), ('historical_map_slug', 8), ('height_px', 9)]], {})})),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Участник команды',
            },
            bases=('wagtailcore.page',),
        ),
    ]
