# Generated by Django 5.1.15 on 2026-05-23 15:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_articlepage_body_alter_eventpage_body_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Короткое описание платформы. Покажется над картой.', verbose_name='Вступительный текст (над картой)')),
                ('initial_lng', models.FloatField(default=110.0, help_text='Долгота центра карты при открытии', verbose_name='Начальная долгота')),
                ('initial_lat', models.FloatField(default=62.0, help_text='Широта центра карты при открытии', verbose_name='Начальная широта')),
                ('initial_zoom', models.FloatField(default=4.0, help_text='Чем больше, тем сильнее приближено (0 = весь мир, 18 = улица)', verbose_name='Начальный зум')),
            ],
            options={
                'verbose_name': 'Платформа (карта)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
